dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - python -m spacy download en_core_web_sm
  - cd extractacy
  - python -m pytest test.py